spring.application.name=Nexus-Meet

# Google OAuth2 Login Settings (Secure Environment Variables)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Fix proxy headers for Render HTTPS redirect
server.forward-headers-strategy=native
server.tomcat.use-relative-redirects=true