spring.application.name=Nexus-Meet

# Google OAuth2 Login Settings (Secure Environment Variables)
spring.security.oauth2.client.registration.google.client-id=127005441943-obif25ib4lkn6c2pv079uku9l5kf14ep.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}